### ISSUE TITLE
Experiencing white screen 

### ISSUE THREAD

**Issue by eqcq** [Bodmer/TFT_eSPI#452] opened 2019-10-29 04:44 UTC
Hi Bodmer and thanks a lot for the library.

I have an esp32 30 pins and a 320x240 ili9341. I created a user setting file like the code under.
Sometimes something display, sometimes no. Wiring seems good, and sometimes when everything is displayed suddenly with no reason screen become white after a display modification (adding a word or rectangle ...). 

Have you any idea ?

Thanks for all
```
#define ILI9341_DRIVER
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   5  // Chip select control pin
#define TFT_DC    26  // Data Command control pin
#define TFT_RST   27  // Reset pin (could connect to RST pin)

//#define USE_HSPI_PORT
#define SUPPORT_TRANSACTIONS

#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

#define SMOOTH_FONT

// #define SPI_FREQUENCY  27000000
#define SPI_FREQUENCY  40000000
// #define SPI_FREQUENCY  80000000

#define SPI_READ_FREQUENCY  20000000

#define SPI_TOUCH_FREQUENCY  2500000

// #define SUPPORT_TRANSACTIONS `

**Comment by Bodmer** [comment] 2019-10-29 20:15
Check your connections, power the display from 5V if it is fitted with a voltage regulator. Don't for get the GND connection.

Test using an example sketch rather than something you have created to check operation.

If this advice fails provide pictures of your setup.

**Comment by kitecraft** [comment] 2019-10-31 01:03
First, yes, Bodmer, this is a great library.  I love the Sprites.  So cool.  And the library is so fast that my display doesn't even blink despite the large number of updates per second.  
However, I've been experiencing the same problem and have been unable to trace any error.  After anywhere from 10 minutes to a few hours of running, the screen suddenly just goes white.  The program is still running without problems.  I know this because of serial output as well as the touch screen still works.  Again, i know this from serial output.  I've added a filter cap to the power but that didn't help either.  
I'll try powering with 5v and report back.  Otherwise, this problem is completely baffling me.

**Comment by Bodmer** [comment] 2019-11-01 01:09
Post a link to your ESP32 board and display and I will see if I can see anything special about your setup.

**Comment by eqcq** [comment] 2019-11-01 01:23
Hi there I finally found an issue with those settings : 
```
#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   5  // Chip select control pin
#define TFT_DC    16  // Data Command control pin
#define TFT_RST   -1  // Reset pin (could connect to RST pin
```)
and I've changed the  SPI_FREQUENCY to  27000000, above create some bugs.
With that it's correct and stable since 3 days

**Comment by kitecraft** [comment] 2019-11-01 01:37
Thanks Bodmer.
Finding this specific board is a bit hard it seems.  But it's this one:  https://lastminuteengineers.com/esp32-arduino-ide-tutorial/
The only links I can find for the TFT are on ebay and amazon.  https://www.ebay.ca/itm/1pc-2-8inches-TFT-LCD-Display-Touch-Panel-SPI-Serial-ILI9341-STM32-Module-Parts-/392506408063?oid=201950756171

I am running mine @ 27mhz.  I'm going to drop it to 20 and see if that helps.

**Comment by eqcq** [comment] 2019-11-01 02:08
Hi Kitecraft reset pin set to -1 and wired on 3.3v helped too in my case

**Comment by eqcq** [comment] 2019-11-01 02:18
@kitecraft is there something engraved on the back of your board ? I've two of those type  engraved DOIT esp32 devekit1 on the back (in little)

**Comment by kitecraft** [comment] 2019-11-01 12:27
@eqcq The only thing on the back of mine is 'esp32s' in ink.  

I've been trying different SPI frequencies, as well as changing the RST pin as you described.  I'm still encountering the issue.  
I'm now trying to write a test program that will reproduce the issue.

**Comment by eqcq** [comment] 2019-11-01 12:58
@kitecraft ok with this board you've to select NodeMCU ESP-32S

**Comment by eqcq** [comment] 2019-11-01 13:02
Now that everything was fine for me; I've tried to set fequency back to : SPI_FREQUENCY  40000000 and I'm experiencing same problem that before. In my case frequency seems to be te key.

**Comment by kitecraft** [comment] 2019-11-01 14:44
Ok, I seem to have a reproducible test case now.  
[TFT_Sprite_Testing.zip](https://github.com/Bodmer/TFT_eSPI/files/3798362/TFT_Sprite_Testing.zip)
My User_Setup.h is included.
I hope it helps.  
Thank you for looking into this Bodmer.  

@eqcq   Perhaps you could also try the test case and see it if reproduces the issue for you.

**Comment by Bodmer** [comment] 2019-11-01 22:34
I have run you test sketch for 6 hours and it worked fine.

Check your setup, simplify down to just the display and ESP32.

Maybe the display is overheating?

**Comment by kitecraft** [comment] 2019-11-01 23:20
Thanks for looking Bodmer.

**Comment by kitecraft** [comment] 2019-11-02 12:25
Update:  (last one from me I guess)
This whitescreen problem seems to be only on that one specific type of board.  I've reproduced the issue on 2 boards and 2 displays (and combinations thereof).  Also, previous issues that came up during development indicate that there is some odd problem there (I can go into detail if you want),

I also happen to have a couple of the NodeMCU ESP-32S boards (https://docs.zerynth.com/latest/official/board.zerynth.nodemcu_esp32/docs/index.html) and the whitescreen is not happening on these boards (using the same displays).

So, thank you for your time Bodmer. I do appreciate you paying attention to this issue.  
And again, great library.  So useful.
You can close this issue as you like.  

Thank you.

ps.  For what it's worth, I've been a software QA Analyst and tester for the last 20 years.  So, I'm not your Average Joe when It comes to testing for issues.  However I am not an experienced developer of any type so my code is probably not written good.

**Comment by Bodmer** [comment] 2019-11-02 12:51
Glad to hear you have it sorted. Your tests suggest this is a hardware related problem.

**Closed by Bodmer** 2019-11-02 12:51 UTC

**Comment by ufuk5619** [comment] 2021-12-29 08:22
Hi @kitecraft ,ı have same problem . I am using st7735 1.8 with stm32f100 mcu. for 10 to few hours it works without problem but later screen goes compeletly white.Even ı reset the board or cut the energy  its still white. Do you have any idea or any result what could be the reason.I think it is about hardware side but cant find any mistake.

**Comment by Bodmer** [comment] 2021-12-29 16:54
You may be running out of RAM, it is difficult to determine the exact cause without a detailed knowledge of the hardware and software you are running. Other possible reasons for spurious problems are EMC (long ignal wires, porr GND(0V connections) voltage spikes from motors and relays etc) and an inadequate power supply.

**Comment by elisabethLC** [comment] 2022-03-31 05:24
Hi, I have the same problem too, I am using ESP32 with 320x240 ILI9488. few days i work with my project TFT ILI9488 works fine but after i upload more code screen goes white but touch screen and SD card still works fine.

**Comment by ufuk5619** [comment] 2022-03-31 06:04
hi @elisabethLC  ı want to ask you something about lcd, are you using  lcd module or are you soldering lcd screen to any pcb. I am asking this because ı had same problems, now ı think ı solved my problems.The cause is soldering with solder paste cause some kind of effect with time and temperature. I am using no clean flux and soldering lcd so carefully and we didnt receive any error until now.

**Comment by elisabethLC** [comment] 2022-03-31 06:42
I am not directly soldering lcd screen to my pcb, I'm using pin header. I already double check the wiring and there is no problem. I tried to use breadboard with new wiring without soldering any pins and run simple code but it is not working either.

**Comment by elisabethLC** [comment] 2022-03-31 08:15
I have fixed my problem, I found something wrong with ESP3 maybe because I wrote wrong algorithm and SRAM overflowed. now works fine with new esp32. Thank you for answering my question.

**Comment by 2ant** [comment] 2022-04-21 05:18
I may have something usefull to add, i got 3 ESP32 DEV KIT V2 from AZDELIVERY and i tested one. The transfer was ok once i used the boot PIN but the test was either partially or totally white. I unplugged it from my computer and plugged it on an usb powerbank and everything was crystal clear. I didn't know a lack of power could make the screen whiter.

**Comment by ciobania** [comment] 2022-05-02 14:05
I have the same issue with screen going white after some time, and could never figure out why. 
I use a Raspberry Pi Zero 2 W, and couple of sensors, for a "SMART" thermostat.

I'll try to up the power supply to 2A, and see if that helps my case.
Thanks for sharing your experiences.

**Comment by GreaseMonkey88** [comment] 2023-05-24 11:56
In my case, connecting the TFT_RST pin worked!

**Comment by sahasradal** [comment] 2025-08-12 07:53
add a 4.7k pullup to the cs pin of aliexpress st7735 lcd

**Comment by slsbold** [comment] 2026-02-17 01:05
I have read dozens of threads about this issue and have found that correct power and soldering is the key. When I looked real close to what I thought was a good joint using Android's Magnifier app, the solder was not making contact with the board's connection ring. I resoldered the connection, paying special attention to the called-out pins in the code and the GND pin. I am now on day 8 running 24/7 with no issue. I am not saying there aren't other possible issues, but cold solder joints and power are the top reasons I have seen across multiple channels. I recommend downloading the Magnifier app or getting a really good magnifyimng glass and look at the joints board edge on and you might just find your issue.

**Comment by Bodmer** [comment] 2026-02-17 15:25
> I have read dozens of threads about this issue and have found that correct power and soldering is the key. When I looked real close to what I thought was a good joint using Android's Magnifier app, the solder was not making contact with the board's connection ring. I resoldered the connection, paying special attention to the called-out pins in the code and the GND pin. I am now on day 8 running 24/7 with no issue. I am not saying there aren't other possible issues, but cold solder joints and power are the top reasons I have seen across multiple channels. I recommend downloading the Magnifier app or getting a really good magnifyimng glass and look at the joints board edge on and you might just find your issue.

Yes, this can be a cause. The prototype boards with push in wires are not very reliable and have poor contacts that oxidise with time.  I also use push on header/jumper wires that cause issues, inside there is a pressure crimp that is poor and causes intermittent connections. The displays are particularly sensitive to glitches as a bad/corrupt command can get them into a lockup white screen state where only a power cycle clears it.  The Espressif IDF has also had memory leaks in the past, particularly in WiFi link applications and that has cause RAM to run out and to corrupt critical arrays. I think things have improved over the last few years but of all the software tools I have worked with I found the ESP IDF to be the most bug ridden and there have been so many changes that have broken this library (mainly the bare metal code and calls required for speed). Espressif seems to be putting much more effort into it now.
